services:
  frontend:
    build:
      context: frontend
    ports:
      - 8080:80
    depends_on:
      - backend

  backend:
    build:
      context: backend
    depends_on:
      - database
    secrets:
      - database_password
    environment:
      DATABASE_URL: postgresql://postgres@database/todo-db
      DATABASE_PASSWORD_FILE: /run/secrets/database_password

  database:
    image: postgres
    secrets:
      - database_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/database_password
      POSTGRES_DB: todo-db
    volumes:
      - ./data:/var/lib/postgresql/data

secrets:
  database_password:
    environment: DATABASE_PASSWORD
